### ISSUE TITLE
APIモック作成

### ISSUE THREAD

**Issue by inoh** [systemlink/web-front-study#11]
Blueprint使って簡単にモック作れないだろうか
https://www.npmjs.com/package/api-mock

**Comment by inoh** [comment]
@kkawazoe こういうのもある
https://apiary.io/

**Comment by inoh** [comment]
http://private-f17f6-webfrontstudy.apiary-mock.com/questions

**Comment by kkawazoe** [comment]
apiaryを使用する事で環境構築としてはclose
