### ISSUE TITLE
リフォーム場所画面を作成

### ISSUE THREAD

**Issue by inoh** [systemlink/web-front-study#21]
## 概要
- [x] ナビゲーション
- [x] 横幅 767px 以下でナビゲーションも２行打ち
- [x] 横幅 1024px 固定でデザインが同じになること
- [x] 横幅 767px 以下で選択画面と選択結果で２行打ち
- [x] ヘッダー固定
- [x] フッター固定

## UI
1024px
![image](https://user-images.githubusercontent.com/1096516/27206477-de3217b6-5272-11e7-89c1-0357b79ca86d.png)

< 768px
![image](https://user-images.githubusercontent.com/1096516/27206515-f35160ac-5272-11e7-9ec8-3b80123048aa.png)

**Comment by kkawazoe** [comment]
@Wataaki 
どんな感じ？
困ってたら遠慮なく言ってください。

**Comment by wataaki** [comment]
これで全画面終了です。
予定より遅くなりましたが、完成してよかったです。
ありがとうございました！

**Comment by inoh** [comment]
@Wataaki お疲れ様ですー :+1:
CSSむずいですけどjsもまた違う難しさがあるので引き続きよろしくです。
